# Generated by Django 2.2.6 on 2019-10-28 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placetype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('add_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='placetype.PlaceType')),
            ],
        ),
    ]
