# Generated by Django 2.2.6 on 2019-11-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
    ]
