# Generated by Django 2.2.6 on 2019-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_for_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
