from django.db import models
from datetime import datetime

from realtors.models import Realtor
from realestates.models import RealEstate
from hometype.models import HomeType
from nearbyplaces.models import NearbyPlaces

class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    realestate = models.ForeignKey(RealEstate, on_delete=models.DO_NOTHING)
    home_type = models.ForeignKey(HomeType, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    total_rooms = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    garage = models.IntegerField(default=0)
    parking_lot = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    is_featured = models.BooleanField(default=False)
    is_sold = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)
    floor_plan_image1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    floor_plan_image2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    floor_plan_image3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    floor_plan_image4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    floor_plan_image5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_7 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_8 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_9 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_10 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_11 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_12 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_13 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_14 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_15 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_16 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_17 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_18 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_19 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_20 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_21 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_22 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_23 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_24 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_25 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_26 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_27 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_28 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_29 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_30 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_31 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_32 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_33 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_34 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_35 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_36 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_37 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_38 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_39 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_40 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_41 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_42 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_43 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_44 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_45 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_46 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_47 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_48 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_49 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_50 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.title


